### PR TITLE
sr_RS - Serbian translation

### PR DESCRIPTION
**Pull request by lukapaunovic**
Add mo

I translated theme to Serbian :)

### CODE REVIEW

**Comment by EvanHerman** [comment]
Thanks so much @lukapaunovic,

I'll give this a review and get it merged in for the 1.7.0 release of Primer. We really appreciate taking the time to translate Primer into Serbian. This is going to be beneficial to a large number of users!


Evan

**Comment by EvanHerman** [comment]
Hi @lukapaunovic 

Can you remove the .mo file from the PR and upload just the .po file. We generate the .po files using grunt - so we'll need the .po file to wrap that up. If you can attach that here and remove the .mo file I'll go ahead and merge everything in and update the develop branch in preparation for 1.7.0.


Best,
Evan

**Review by EvanHerman — CHANGES_REQUESTED** [review]
@lukapaunovic Can you remove the .mo file here and attach the .po? I'll get everything merged once we have the .po file.

**Comment by lukapaunovic** [comment]
@EvanHerman  I did that as soon I saw your message, why didn't you merged it in 1.7.0 ?

**Comment by EvanHerman** [comment]
@lukapaunovic unfortunately I don't speak Serbian so I can't verify that all of the strings. We are passing this along to some of our Serbian team members to review and will get this merged in once we hear back from them. 

Evan

**Comment by lukapaunovic** [comment]
Please note that is in Serbian LATIN, i can also do Serbian Cyrillic

**Review by EvanHerman — APPROVED** [review]

**Pull request merged**
