### PR TITLE
Hero edit link

### PR DESCRIPTION
**Pull request by jonathanbardo**
@fjarrett This is what I've got so far. It basically adds an edit link after the widget like we are doing for contact widgets. 

I was hesitant on putting the edit link before. What do you think?

### CODE REVIEW

**Comment by frankiejarrett** [comment]
@jonathanbardo Any reason why the Edit link is outside of the `aside.widget` container?

**Comment by jonathanbardo** [comment]
@fjarrett No particular reasons actually.

**Comment by frankiejarrett** [comment]
@jonathanbardo I think it should be then, because otherwise it doesn't follow the rules when it comes to widget margins. The "Edit" link on posts is always inside the `.hentry` container, for example.

screen shot 2016-08-17 at 12 44 46 pm

**Comment by jonathanbardo** [comment]
@fjarrett done in cce3858

**Comment by frankiejarrett** [comment]
@jonathanbardo Much nicer.

screen shot 2016-08-17 at 12 47 00 pm

**Comment by jonathanbardo** [comment]
@fjarrett I think we should plan to add some theme specific style to this as well.

**Comment by frankiejarrett** [comment]
@jonathanbardo What do you have in mind? This looks/feels very much like the Edit links on posts, which I think we should emulate.

**Comment by jonathanbardo** [comment]
@fjarrett It seems some padding on escapade actually... That's all I've seen so far.

**Comment by jonathanbardo** [comment]
Closing this, seems like plugin territory for now.

**Pull request closed without merging**
