### PR TITLE
Reduce WooCommerce button font size when site is not English

### LINKED ISSUE #110: 'Add to Cart'/'Select Options' links overlap on certain languages
On certain languages the 'Add to Cart' and/or 'Select Options' links overlap and overflow on the shop page. 

Setting `max-width: 100%;` resolves the links overflowing, but the font-size still causes the text to overflow outside the links. (_not an issue in English_)

Overlapping Links

### PR DESCRIPTION
**Pull request by frankiejarrett**
Fixes #110 

I was not sure exactly how many languages are affected by this, so the PR here will add the body class `primer-woocommerce-l10n` when WooCommerce is being localized.

### CODE REVIEW

**Comment by frankiejarrett** [comment]
@EvanHerman Please review

**Comment by EvanHerman** [comment]
@fjarrett After some review there were still a few languages that were causing some issues. Even though the text was smaller, the buttons were slightly overflowing outside of the parent container (in german, but I assume other languages might overflow further). 

Example

Even with a max-width: 100% set there was some weirdness going on after adding an item to the cart. Also the success message was overflowing:

Example


I made a few adjustments in my commit. WooCommerce sets the `white-space` to `nowrap` which is why the text wasn't breaking to a new line. On the `.primer-woocommerce-l10n .button` and the `.woocommerce a.added_to_cart` (success message) elements I went ahead and:

- set the `white-space` to `normal`
- set a `max-width` of `100%`
- set `text-align` to `center`
- set `display` to `block`

Results:
example

This should take care of the overlapping/overflow issue on i10n sites.

**Comment by EvanHerman** [comment]
@fjarrett If we go the route proposed above, maybe we don't need to set the `font-size` to `0.75rem`. Personally I think that it looks good at that size, but if we want to keep it universal between english and other languages it may not be necessary.

**Comment by frankiejarrett** [comment]
@EvanHerman I'm not concerned about keeping presentation universal between languages, the only ones who notice that is us. As long as we find an approach that can be _applied_ somewhat universally that causes each given local to look presentable, I'm happy.

**Comment by frankiejarrett** [comment]
Sorry, I accidentally closed the PR 😸

**Comment by EvanHerman** [comment]
@fjarrett If you're cool with the changes above, I think this can be re-reviewed for merge.

**Comment by frankiejarrett** [comment]
@EvanHerman I pulled your changes and ran `grunt`, and it said there were changes to some styles, so I commited those in https://github.com/godaddy/wp-primer-theme/pull/167/commits/05f6e391f9fd76e606089cb1ec1617cdb062b875. You might need to run `npm install` on your local.

**Comment by frankiejarrett** [comment]
@EvanHerman On the lower spectrum of the tablet breakpoint there is some breakage.

**Comment by EvanHerman** [comment]
@fjarrett You're right. I shifted the styles outside of the breakpoint, and left the font-size in there. That seems to have resolved things.

**Review by EvanHerman — APPROVED** [review]

**Comment by frankiejarrett** [comment]
@EvanHerman I assume we need to add these styles to all the child themes as well?

**Comment by EvanHerman** [comment]
@fjarrett Yes, I am working on that now. I should have a PR for a few of the themes tonight.

**Pull request merged**
